exclude: "^docs/|/migrations/|devcontainer.json|.*.html|.*.css|.*.js|.*.svg|.*.dist"

default_language_version:
  python: python3.13

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^tests/artifacts/
      - id: end-of-file-fixer
        exclude: ^tests/artifacts/
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: detect-private-key

  # Run the Ruff linter.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2
    hooks:
      # Linter
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        exclude: ^tests/artifacts/
      # Formatter
      - id: ruff-format
        exclude: ^tests/artifacts/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1  # check for the latest version
    hooks:
      - id: autoflake
        args: [
          "--in-place",
          "--remove-all-unused-imports",
          "--remove-unused-variables",
          "--expand-star-imports"
        ]
        additional_dependencies: ["autoflake"]

# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
