# ======================= EXAMPLE `variants.toml` FILE ====================== #

# ============================== Priority lists ============================= #

# The following lists are used to override the default priorities used
# by variantlib.  The values listed will be bumped up to the highest priority,
# in the listed order (most preferred first).  The value not in the lists
# will be given subsequent priorities, according to the default order defined
# by packages and provider plugins.

# Note that all values are strings -- numeric values need to be quoted.

# 1. Adjusting namespace priorities.
namespace_priorities = [
    "fictional_hw",
    "fictional_tech",
    "simd_x86_64",
    "non_existent_provider",
]

# 2. Adjusting priorities of features within a namespace.
feature_priorities.fictional_hw = ["architecture"]
feature_priorities.fictional_tech = ["risk_exposure"]
feature_priorities.simd_x86_64 = ["feature3"]

# 3. Adjusting priorities of property values within a feature.
property_priorities.fictional_hw.architecture = ["mother"]
property_priorities.fictional_tech.risk_exposure = ["25"]
