# ======================= EXAMPLE `variants.toml` FILE ====================== #

# ============= Top-Most Priority ============= #

# 1. Define the variant properties `VariantProperty` to "bump to the top of the priority list"
#     Expected format: "namespace::feature::value"
# OPTIONAL: In most cases - the user will not specify the following
# Note: This is a lazy-list: Only specify the ones you want to "bump up" to the top of the list
property_priority = [
    "fictional_hw::architecture::mother",
    "fictional_tech::risk_exposure:25",
]

# ============= Second-Most Priority ============= #

# 2. Define the variant features: `VariantFeature` to "bump to the top of the priority list" 
#     These come after the ones defined in 1) [`property_priority`]
# Expected format: "namespace::feature"
# OPTIONAL: In most cases - the user will not specify the following
# Note: This is a lazy-list: Only specify the ones you want to "bump up" to the top of the list
features_priority = [
    "fictional_hw::architecture",
    "fictional_tech::risk_exposure",
    "simd_x86_64::feature3",
]

# ============= Default Priority Ordering ============= #

# 3. Define the variant namespaces by priority
# MANDATORY: as long as there is more than 1 variant plugin installed. This field must be specified
#                          If not one installed plugin is missing => should error out. 
#                          Namespaces can be specified but not installed.
namespaces_priority = [
    "fictional_hw",
    "fictional_tech",
    "simd_x86_64",
    "non_existent_provider",
]
